// src/styles/theme.ts
import { MD3LightTheme } from 'react-native-paper';

export const theme = {
    ...MD3LightTheme,
    colors: {
        ...MD3LightTheme.colors,
        primary: '#6200EE',
        primaryContainer: '#EADDFF',
        secondary: '#625B71',
        secondaryContainer: '#E8DEF8',
        tertiary: '#7D5260',
        tertiaryContainer: '#FFD8E4',
        surface: '#FFFBFE',
        surfaceVariant: '#E7E0EC',
        background: '#FFFBFE',
        error: '#BA1A1A',
        errorContainer: '#FFDAD6',
        onPrimary: '#FFFFFF',
        onPrimaryContainer: '#21005D',
        onSecondary: '#FFFFFF',
        onSecondaryContainer: '#1D192B',
        onTertiary: '#FFFFFF',
        onTertiaryContainer: '#31111D',
        onSurface: '#1C1B1F',
        onSurfaceVariant: '#49454F',
        onError: '#FFFFFF',
        onErrorContainer: '#410002',
        onBackground: '#1C1B1F',
        outline: '#79747E',
        outlineVariant: '#CAC4D0',
        inverseSurface: '#313033',
        inverseOnSurface: '#F4F0F4',
        inversePrimary: '#D0BCFF',
        shadow: '#000000',
        scrim: '#000000',
        surfaceDisabled: 'rgba(28, 27, 31, 0.12)',
        onSurfaceDisabled: 'rgba(28, 27, 31, 0.38)',
        backdrop: 'rgba(73, 69, 79, 0.4)',
    },
};